### ISSUE TITLE
Code Review Suggestions

### ISSUE THREAD

**Issue by arnima-agg** [starydv7/sordid-worm-4067#56]
- You have try to add more functionality to the project that is good.
- Project has good features try to make them dynamic.
- Code quality is overall good except some naming conventions - https://github.com/starydv7/sordid-worm-4067/blob/56c0101ea0668652e4add791bfb889674cd2766a/src/pages/CheckOut.css. This is very bad try to change this.
- Remove commented code and add meaningful comments
- Github commit history is not so good. Why only one person has  committed most of the features  and in the single commit - https://github.com/starydv7/sordid-worm-4067/commit/55fabe026ec901f1fdc63a9528fc0cb0d7178b08
- Try to write meaningful commits.
- Website is not responsive. Make it responsive.
- Youtube videos that you have added, framing can be better for them.
- Certain features in UI can be improved like navbar.
- Update ReadMe with your videos description and something about the project - https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/

**Comment by starydv7** [comment]
Thank You.I will make changes as per your suggestion and try to make this
responsive and also try to add some features.
Thank your valuable time .
Thanks and Regards
Pawan Yadav

**Comment by starydv7** [comment]
Close with Resolution try to improve more later
